In [17]:
import os

In [18]:
os.getcwd()

'C:\\Users\\priya'

In [19]:
import pandas as pd

In [20]:
data1 = pd.read_csv("CAvideos.csv")
data1.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...

In [21]:
import json
with open("CA_category_id.json") as json_file:
         data = json.load(json_file)
        
print(data)
type(data)

{'kind': 'youtube#videoCategoryListResponse', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2qTj13hkQZk"', 'items': [{'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKmPBggty2mZQ"', 'id': '1', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Film & Animation', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45ZTFR3a3NyTA"', 'id': '2', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Autos & Vehicles', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxbknKFVe5Lmg"', 'id': '10', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Music', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-oBJavSGkfDI"', 'id': '15', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Pets & Animals', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM1XVQ9zbGec"', 'id': '17', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Sports', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/FJwVpGCVZ1yiJrqZbpqe68Sy_OE"', 'id': '18', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Short Movies', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/M-3iD9dwK7YJCafRf_DkLN8CouA"', 'id': '19', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Travel & Events', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/WmA0qYEfjWsAoyJFSw2zinhn2wM"', 'id': '20', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Gaming', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/EapFaGYG7K0StIXVf8aba249tdM"', 'id': '21', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Videoblogging', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/xId8RX7vRN8rqkbYZbNIytUQDRo"', 'id': '22', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'People & Blogs', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/G9LHzQmx44rX2S5yaga_Aqtwz8M"', 'id': '23', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Comedy', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/UVB9oxX2Bvqa_w_y3vXSLVK5E_s"', 'id': '24', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Entertainment', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/QiLK0ZIrFoORdk_g2l_XR_ECjDc"', 'id': '25', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'News & Politics', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/r6Ck6Z0_L0rG37VJQR200SGNA_w"', 'id': '26', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Howto & Style', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/EoYkczo9I3RCf96RveKTOgOPkUM"', 'id': '27', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Education', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/w5HjcTD82G_XA3xBctS30zS-JpQ"', 'id': '28', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Science & Technology', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/lL7uWDr_071CHxifjYG1tJrp4Uo"', 'id': '30', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Movies', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/WnuVfjO-PyFLO7NTRQIbrGE62nk"', 'id': '31', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Anime/Animation', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/ctpH2hGA_UZ3volJT_FTlOg9M00"', 'id': '32', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Action/Adventure', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/L0kR3-g1BAo5UD1PLVbQ7LkkDtQ"', 'id': '33', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Classics', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/pUZOAC_s9sfiwar639qr_wAB-aI"', 'id': '34', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Comedy', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/Xb5JLhtyNRN3AQq021Ds-OV50Jk"', 'id': '35', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Documentary', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/u8WXzF4HIhtEi805__sqjuA4lEk"', 'id': '36', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Drama', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/D04PP4Gr7wc4IV_O9G66Z4A8KWQ"', 'id': '37', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Family', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/i5-_AceGXQCEEMWU0V8CcQm_vLQ"', 'id': '38', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Foreign', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/rtlxd0zOixA9QHdIZB26-St5qgQ"', 'id': '39', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Horror', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/N1TrDFLRppxZgBowCJfJCvh0Dpg"', 'id': '40', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Sci-Fi/Fantasy', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/7UMGi6zRySqXopr_rv4sZq6Za2E"', 'id': '41', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Thriller', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/RScXhi324h8usyIetreAVb-uKeM"', 'id': '42', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Shorts', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiGVrFsuFsd0A"', 'id': '43', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Shows', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/x5NxSf5fz8hn4loSN4rvhwzD_pY"', 'id': '44', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Trailers', 'assignable': False}}]}

dict

In [22]:
with open("CA_category_id.json") as json_file:
         data = json.load(json_file)
        
print(data)
type(data)

{'kind': 'youtube#videoCategoryListResponse', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2qTj13hkQZk"', 'items': [{'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKmPBggty2mZQ"', 'id': '1', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Film & Animation', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45ZTFR3a3NyTA"', 'id': '2', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Autos & Vehicles', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxbknKFVe5Lmg"', 'id': '10', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Music', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-oBJavSGkfDI"', 'id': '15', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Pets & Animals', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM1XVQ9zbGec"', 'id': '17', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Sports', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/FJwVpGCVZ1yiJrqZbpqe68Sy_OE"', 'id': '18', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Short Movies', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/M-3iD9dwK7YJCafRf_DkLN8CouA"', 'id': '19', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Travel & Events', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/WmA0qYEfjWsAoyJFSw2zinhn2wM"', 'id': '20', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Gaming', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/EapFaGYG7K0StIXVf8aba249tdM"', 'id': '21', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Videoblogging', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/xId8RX7vRN8rqkbYZbNIytUQDRo"', 'id': '22', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'People & Blogs', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/G9LHzQmx44rX2S5yaga_Aqtwz8M"', 'id': '23', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Comedy', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/UVB9oxX2Bvqa_w_y3vXSLVK5E_s"', 'id': '24', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Entertainment', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/QiLK0ZIrFoORdk_g2l_XR_ECjDc"', 'id': '25', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'News & Politics', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/r6Ck6Z0_L0rG37VJQR200SGNA_w"', 'id': '26', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Howto & Style', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/EoYkczo9I3RCf96RveKTOgOPkUM"', 'id': '27', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Education', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/w5HjcTD82G_XA3xBctS30zS-JpQ"', 'id': '28', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Science & Technology', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/lL7uWDr_071CHxifjYG1tJrp4Uo"', 'id': '30', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Movies', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/WnuVfjO-PyFLO7NTRQIbrGE62nk"', 'id': '31', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Anime/Animation', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/ctpH2hGA_UZ3volJT_FTlOg9M00"', 'id': '32', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Action/Adventure', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/L0kR3-g1BAo5UD1PLVbQ7LkkDtQ"', 'id': '33', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Classics', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/pUZOAC_s9sfiwar639qr_wAB-aI"', 'id': '34', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Comedy', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/Xb5JLhtyNRN3AQq021Ds-OV50Jk"', 'id': '35', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Documentary', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/u8WXzF4HIhtEi805__sqjuA4lEk"', 'id': '36', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Drama', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/D04PP4Gr7wc4IV_O9G66Z4A8KWQ"', 'id': '37', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Family', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/i5-_AceGXQCEEMWU0V8CcQm_vLQ"', 'id': '38', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Foreign', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/rtlxd0zOixA9QHdIZB26-St5qgQ"', 'id': '39', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Horror', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/N1TrDFLRppxZgBowCJfJCvh0Dpg"', 'id': '40', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Sci-Fi/Fantasy', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/7UMGi6zRySqXopr_rv4sZq6Za2E"', 'id': '41', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Thriller', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/RScXhi324h8usyIetreAVb-uKeM"', 'id': '42', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Shorts', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiGVrFsuFsd0A"', 'id': '43', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Shows', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/x5NxSf5fz8hn4loSN4rvhwzD_pY"', 'id': '44', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Trailers', 'assignable': False}}]}

dict

In [23]:
df = pd.Series(data, index = ['kind', 'etag', 'items'])

In [24]:
df.head()

kind                     youtube#videoCategoryListResponse
etag     "ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...
items    [{'kind': 'youtube#videoCategory', 'etag': '"l...
dtype: object

In [25]:
type(df)

pandas.core.series.Series

In [26]:
df4 = df['items']

In [27]:
type(df4)

list

In [28]:
print(df4)

[{'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKmPBggty2mZQ"', 'id': '1', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Film & Animation', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45ZTFR3a3NyTA"', 'id': '2', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Autos & Vehicles', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxbknKFVe5Lmg"', 'id': '10', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Music', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-oBJavSGkfDI"', 'id': '15', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Pets & Animals', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM1XVQ9zbGec"', 'id': '17', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Sports', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/FJwVpGCVZ1yiJrqZbpqe68Sy_OE"', 'id': '18', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Short Movies', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/M-3iD9dwK7YJCafRf_DkLN8CouA"', 'id': '19', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Travel & Events', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/WmA0qYEfjWsAoyJFSw2zinhn2wM"', 'id': '20', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Gaming', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/EapFaGYG7K0StIXVf8aba249tdM"', 'id': '21', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Videoblogging', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/xId8RX7vRN8rqkbYZbNIytUQDRo"', 'id': '22', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'People & Blogs', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/G9LHzQmx44rX2S5yaga_Aqtwz8M"', 'id': '23', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Comedy', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/UVB9oxX2Bvqa_w_y3vXSLVK5E_s"', 'id': '24', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Entertainment', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/QiLK0ZIrFoORdk_g2l_XR_ECjDc"', 'id': '25', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'News & Politics', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/r6Ck6Z0_L0rG37VJQR200SGNA_w"', 'id': '26', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Howto & Style', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/EoYkczo9I3RCf96RveKTOgOPkUM"', 'id': '27', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Education', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/w5HjcTD82G_XA3xBctS30zS-JpQ"', 'id': '28', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Science & Technology', 'assignable': True}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/lL7uWDr_071CHxifjYG1tJrp4Uo"', 'id': '30', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Movies', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/WnuVfjO-PyFLO7NTRQIbrGE62nk"', 'id': '31', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Anime/Animation', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/ctpH2hGA_UZ3volJT_FTlOg9M00"', 'id': '32', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Action/Adventure', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/L0kR3-g1BAo5UD1PLVbQ7LkkDtQ"', 'id': '33', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Classics', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/pUZOAC_s9sfiwar639qr_wAB-aI"', 'id': '34', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Comedy', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/Xb5JLhtyNRN3AQq021Ds-OV50Jk"', 'id': '35', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Documentary', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/u8WXzF4HIhtEi805__sqjuA4lEk"', 'id': '36', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Drama', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/D04PP4Gr7wc4IV_O9G66Z4A8KWQ"', 'id': '37', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Family', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/i5-_AceGXQCEEMWU0V8CcQm_vLQ"', 'id': '38', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Foreign', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/rtlxd0zOixA9QHdIZB26-St5qgQ"', 'id': '39', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Horror', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/N1TrDFLRppxZgBowCJfJCvh0Dpg"', 'id': '40', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Sci-Fi/Fantasy', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/7UMGi6zRySqXopr_rv4sZq6Za2E"', 'id': '41', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Thriller', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/RScXhi324h8usyIetreAVb-uKeM"', 'id': '42', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Shorts', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiGVrFsuFsd0A"', 'id': '43', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Shows', 'assignable': False}}, {'kind': 'youtube#videoCategory', 'etag': '"ld9biNPKjAjgjV7EZ4EKeEGrhao/x5NxSf5fz8hn4loSN4rvhwzD_pY"', 'id': '44', 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'title': 'Trailers', 'assignable': False}}]

In [29]:
type(df4)

list

In [30]:
df5 = pd.DataFrame.from_records(df4)

In [31]:
print(df5)

                                                 etag  id  \
0   "ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...   1
1   "ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...   2
2   "ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...  10
3   "ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...  15
4   "ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...  17
5   "ld9biNPKjAjgjV7EZ4EKeEGrhao/FJwVpGCVZ1yiJrqZb...  18
6   "ld9biNPKjAjgjV7EZ4EKeEGrhao/M-3iD9dwK7YJCafRf...  19
7   "ld9biNPKjAjgjV7EZ4EKeEGrhao/WmA0qYEfjWsAoyJFS...  20
8   "ld9biNPKjAjgjV7EZ4EKeEGrhao/EapFaGYG7K0StIXVf...  21
9   "ld9biNPKjAjgjV7EZ4EKeEGrhao/xId8RX7vRN8rqkbYZ...  22
10  "ld9biNPKjAjgjV7EZ4EKeEGrhao/G9LHzQmx44rX2S5ya...  23
11  "ld9biNPKjAjgjV7EZ4EKeEGrhao/UVB9oxX2Bvqa_w_y3...  24
12  "ld9biNPKjAjgjV7EZ4EKeEGrhao/QiLK0ZIrFoORdk_g2...  25
13  "ld9biNPKjAjgjV7EZ4EKeEGrhao/r6Ck6Z0_L0rG37VJQ...  26
14  "ld9biNPKjAjgjV7EZ4EKeEGrhao/EoYkczo9I3RCf96Rv...  27
15  "ld9biNPKjAjgjV7EZ4EKeEGrhao/w5HjcTD82G_XA3xBc...  28
16  "ld9biNPKjAjgjV7EZ4EKeEGrhao/lL7uWDr_071CHxifj...  30
17  "ld9biNPKjAjgjV7EZ4EKeEGrhao/WnuVfjO-PyFLO7NTR...  31
18  "ld9biNPKjAjgjV7EZ4EKeEGrhao/ctpH2hGA_UZ3volJT...  32
19  "ld9biNPKjAjgjV7EZ4EKeEGrhao/L0kR3-g1BAo5UD1PL...  33
20  "ld9biNPKjAjgjV7EZ4EKeEGrhao/pUZOAC_s9sfiwar63...  34
21  "ld9biNPKjAjgjV7EZ4EKeEGrhao/Xb5JLhtyNRN3AQq02...  35
22  "ld9biNPKjAjgjV7EZ4EKeEGrhao/u8WXzF4HIhtEi805_...  36
23  "ld9biNPKjAjgjV7EZ4EKeEGrhao/D04PP4Gr7wc4IV_O9...  37
24  "ld9biNPKjAjgjV7EZ4EKeEGrhao/i5-_AceGXQCEEMWU0...  38
25  "ld9biNPKjAjgjV7EZ4EKeEGrhao/rtlxd0zOixA9QHdIZ...  39
26  "ld9biNPKjAjgjV7EZ4EKeEGrhao/N1TrDFLRppxZgBowC...  40
27  "ld9biNPKjAjgjV7EZ4EKeEGrhao/7UMGi6zRySqXopr_r...  41
28  "ld9biNPKjAjgjV7EZ4EKeEGrhao/RScXhi324h8usyIet...  42
29  "ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiG...  43
30  "ld9biNPKjAjgjV7EZ4EKeEGrhao/x5NxSf5fz8hn4loSN...  44

                     kind                                            snippet
0   youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
1   youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
2   youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
3   youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
4   youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
5   youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
6   youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
7   youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
8   youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
9   youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
10  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
11  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
12  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
13  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
14  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
15  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
16  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
17  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
18  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
19  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
20  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
21  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
22  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
23  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
24  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
25  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
26  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
27  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
28  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
29  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
30  youtube#videoCategory  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...

In [32]:
type(df5)

pandas.core.frame.DataFrame

In [33]:
df_id = df5.iloc[:,[0,1,2]]
df_id.head()
type(df_id)

pandas.core.frame.DataFrame

In [34]:
df_snippet = df5["snippet"]
df_snippet.head()

0    {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
1    {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
2    {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
3    {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
4    {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
Name: snippet, dtype: object

In [35]:
type(df_snippet)

pandas.core.series.Series

In [36]:
df6 = pd.DataFrame.from_records(df_snippet)

In [37]:
print(df6)

    assignable                 channelId                 title
0         True  UCBR8-60-B28hp2BmDPdntcQ      Film & Animation
1         True  UCBR8-60-B28hp2BmDPdntcQ      Autos & Vehicles
2         True  UCBR8-60-B28hp2BmDPdntcQ                 Music
3         True  UCBR8-60-B28hp2BmDPdntcQ        Pets & Animals
4         True  UCBR8-60-B28hp2BmDPdntcQ                Sports
5        False  UCBR8-60-B28hp2BmDPdntcQ          Short Movies
6         True  UCBR8-60-B28hp2BmDPdntcQ       Travel & Events
7         True  UCBR8-60-B28hp2BmDPdntcQ                Gaming
8        False  UCBR8-60-B28hp2BmDPdntcQ         Videoblogging
9         True  UCBR8-60-B28hp2BmDPdntcQ        People & Blogs
10        True  UCBR8-60-B28hp2BmDPdntcQ                Comedy
11        True  UCBR8-60-B28hp2BmDPdntcQ         Entertainment
12        True  UCBR8-60-B28hp2BmDPdntcQ       News & Politics
13        True  UCBR8-60-B28hp2BmDPdntcQ         Howto & Style
14        True  UCBR8-60-B28hp2BmDPdntcQ             Education
15        True  UCBR8-60-B28hp2BmDPdntcQ  Science & Technology
16       False  UCBR8-60-B28hp2BmDPdntcQ                Movies
17       False  UCBR8-60-B28hp2BmDPdntcQ       Anime/Animation
18       False  UCBR8-60-B28hp2BmDPdntcQ      Action/Adventure
19       False  UCBR8-60-B28hp2BmDPdntcQ              Classics
20       False  UCBR8-60-B28hp2BmDPdntcQ                Comedy
21       False  UCBR8-60-B28hp2BmDPdntcQ           Documentary
22       False  UCBR8-60-B28hp2BmDPdntcQ                 Drama
23       False  UCBR8-60-B28hp2BmDPdntcQ                Family
24       False  UCBR8-60-B28hp2BmDPdntcQ               Foreign
25       False  UCBR8-60-B28hp2BmDPdntcQ                Horror
26       False  UCBR8-60-B28hp2BmDPdntcQ        Sci-Fi/Fantasy
27       False  UCBR8-60-B28hp2BmDPdntcQ              Thriller
28       False  UCBR8-60-B28hp2BmDPdntcQ                Shorts
29       False  UCBR8-60-B28hp2BmDPdntcQ                 Shows
30       False  UCBR8-60-B28hp2BmDPdntcQ              Trailers

In [38]:
final_df = pd.concat([df_id,df6], axis = 1, sort = False)

In [39]:
final_df.head()

,etag,id,kind,assignable,channelId,title
0,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...",1,youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation
1,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...",2,youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles
2,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10,youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music
3,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...",15,youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals
4,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...",17,youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Sports

In [40]:
final_df.dtypes

etag          object
id            object
kind          object
assignable      bool
channelId     object
title         object
dtype: object

In [41]:
final_df.id = final_df.id.astype(int)

In [42]:
final_df.dtypes

etag          object
id             int32
kind          object
assignable      bool
channelId     object
title         object
dtype: object

In [43]:
data1.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...

In [44]:
data1.dtypes

video_id                  object
trending_date             object
title                     object
channel_title             object
category_id                int64
publish_time              object
tags                      object
views                      int64
likes                      int64
dislikes                   int64
comment_count              int64
thumbnail_link            object
comments_disabled           bool
ratings_disabled            bool
video_error_or_removed      bool
description               object
dtype: object

In [45]:
data1.rename(columns = {'category_id' : 'id'}, inplace = True)

In [46]:
data1.dtypes

video_id                  object
trending_date             object
title                     object
channel_title             object
id                         int64
publish_time              object
tags                      object
views                      int64
likes                      int64
dislikes                   int64
comment_count              int64
thumbnail_link            object
comments_disabled           bool
ratings_disabled            bool
video_error_or_removed      bool
description               object
dtype: object

In [47]:
df_final1 = pd.merge(data1, final_df, on = "id")

In [48]:
df_final1.head()

,video_id,trending_date,title_x,channel_title,id,publish_time,tags,views,likes,dislikes,...,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,etag,kind,assignable,channelId,title_y
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music
1,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music
2,H1KBHFXm2Bg,17.14.11,21 Savage - Bank Account (Official Music Video),21 Savage,10,2017-11-10T19:00:02.000Z,"21 savage|""bank account""|""21 savage bank accou...",5068229,263596,8585,...,https://i.ytimg.com/vi/H1KBHFXm2Bg/default.jpg,False,False,False,Watch the official music video of Bank Account...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music
3,7MxiQ4v0EnE,17.14.11,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,10,2017-11-11T16:41:15.000Z,"punjabi songs|""punjabi bhangra""|""punjabi music...",5718766,127477,7134,...,https://i.ytimg.com/vi/7MxiQ4v0EnE/default.jpg,False,False,False,Song - Daang\nSinger - Mankirt Aulakh\nFaceboo...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music
4,j67FgNEvyh8,17.14.11,Telefoon || Babbu Maan || Promo || Full Song 1...,Hey Yolo,10,2017-11-12T04:24:34.000Z,"Telefoon|""Babbu Maan""|""Mehfil Mitran Di""|""new ...",178447,4339,96,...,https://i.ytimg.com/vi/j67FgNEvyh8/default.jpg,False,False,False,"Full Song Out Now 15th November\n\nHey Yolo, S...","""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music

In [49]:
df_final1.dtypes

video_id                  object
trending_date             object
title_x                   object
channel_title             object
id                         int64
publish_time              object
tags                      object
views                      int64
likes                      int64
dislikes                   int64
comment_count              int64
thumbnail_link            object
comments_disabled           bool
ratings_disabled            bool
video_error_or_removed      bool
description               object
etag                      object
kind                      object
assignable                  bool
channelId                 object
title_y                   object
dtype: object

In [50]:
df_final1['trending_date'] = pd.to_datetime(df_final1['trending_date'].str.strip(), format = '%y.%d.%m')

In [51]:
df_final1.head()

,video_id,trending_date,title_x,channel_title,id,publish_time,tags,views,likes,dislikes,...,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,etag,kind,assignable,channelId,title_y
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music
1,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music
2,H1KBHFXm2Bg,2017-11-14,21 Savage - Bank Account (Official Music Video),21 Savage,10,2017-11-10T19:00:02.000Z,"21 savage|""bank account""|""21 savage bank accou...",5068229,263596,8585,...,https://i.ytimg.com/vi/H1KBHFXm2Bg/default.jpg,False,False,False,Watch the official music video of Bank Account...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music
3,7MxiQ4v0EnE,2017-11-14,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,10,2017-11-11T16:41:15.000Z,"punjabi songs|""punjabi bhangra""|""punjabi music...",5718766,127477,7134,...,https://i.ytimg.com/vi/7MxiQ4v0EnE/default.jpg,False,False,False,Song - Daang\nSinger - Mankirt Aulakh\nFaceboo...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music
4,j67FgNEvyh8,2017-11-14,Telefoon || Babbu Maan || Promo || Full Song 1...,Hey Yolo,10,2017-11-12T04:24:34.000Z,"Telefoon|""Babbu Maan""|""Mehfil Mitran Di""|""new ...",178447,4339,96,...,https://i.ytimg.com/vi/j67FgNEvyh8/default.jpg,False,False,False,"Full Song Out Now 15th November\n\nHey Yolo, S...","""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music

In [52]:
df_final1.dtypes

video_id                          object
trending_date             datetime64[ns]
title_x                           object
channel_title                     object
id                                 int64
publish_time                      object
tags                              object
views                              int64
likes                              int64
dislikes                           int64
comment_count                      int64
thumbnail_link                    object
comments_disabled                   bool
ratings_disabled                    bool
video_error_or_removed              bool
description                       object
etag                              object
kind                              object
assignable                          bool
channelId                         object
title_y                           object
dtype: object

In [53]:
df_final1.head(2)

,video_id,trending_date,title_x,channel_title,id,publish_time,tags,views,likes,dislikes,...,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,etag,kind,assignable,channelId,title_y
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music
1,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music

In [54]:
df_final1['month'] = df_final1['trending_date'].dt.month

In [55]:
df_final1['year'] = df_final1['trending_date'].dt.year

In [56]:
df_final1['year'].unique()

array([2017, 2018], dtype=int64)

In [57]:
df_final1['month'].unique()

array([11, 12,  1,  2,  3,  4,  5,  6], dtype=int64)

In [58]:
df_final1.head()

,video_id,trending_date,title_x,channel_title,id,publish_time,tags,views,likes,dislikes,...,ratings_disabled,video_error_or_removed,description,etag,kind,assignable,channelId,title_y,month,year
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music,11,2017
1,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music,11,2017
2,H1KBHFXm2Bg,2017-11-14,21 Savage - Bank Account (Official Music Video),21 Savage,10,2017-11-10T19:00:02.000Z,"21 savage|""bank account""|""21 savage bank accou...",5068229,263596,8585,...,False,False,Watch the official music video of Bank Account...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music,11,2017
3,7MxiQ4v0EnE,2017-11-14,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,10,2017-11-11T16:41:15.000Z,"punjabi songs|""punjabi bhangra""|""punjabi music...",5718766,127477,7134,...,False,False,Song - Daang\nSinger - Mankirt Aulakh\nFaceboo...,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music,11,2017
4,j67FgNEvyh8,2017-11-14,Telefoon || Babbu Maan || Promo || Full Song 1...,Hey Yolo,10,2017-11-12T04:24:34.000Z,"Telefoon|""Babbu Maan""|""Mehfil Mitran Di""|""new ...",178447,4339,96,...,False,False,"Full Song Out Now 15th November\n\nHey Yolo, S...","""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",youtube#videoCategory,True,UCBR8-60-B28hp2BmDPdntcQ,Music,11,2017

In [59]:
df_new = df_final1[["trending_date","title_x","channel_title","id","tags","views","likes","dislikes","title_y","month","year"]]

In [60]:
df_new.head()

,trending_date,title_x,channel_title,id,tags,views,likes,dislikes,title_y,month,year
0,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,Music,11,2017
1,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,Music,11,2017
2,2017-11-14,21 Savage - Bank Account (Official Music Video),21 Savage,10,"21 savage|""bank account""|""21 savage bank accou...",5068229,263596,8585,Music,11,2017
3,2017-11-14,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,10,"punjabi songs|""punjabi bhangra""|""punjabi music...",5718766,127477,7134,Music,11,2017
4,2017-11-14,Telefoon || Babbu Maan || Promo || Full Song 1...,Hey Yolo,10,"Telefoon|""Babbu Maan""|""Mehfil Mitran Di""|""new ...",178447,4339,96,Music,11,2017

In [61]:
export_csv = df_new.to_csv (r'youtubeNew.csv', index = None, header=True)

In [134]:
df_tags = df_new[["id", "title_y","tags"]]

In [135]:
df_tags.head()

   id title_y                                               tags
0  10   Music  Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...
1  10   Music  edsheeran|"ed sheeran"|"acoustic"|"live"|"cove...
2  10   Music  21 savage|"bank account"|"21 savage bank accou...
3  10   Music  punjabi songs|"punjabi bhangra"|"punjabi music...
4  10   Music  Telefoon|"Babbu Maan"|"Mehfil Mitran Di"|"new ...

In [136]:
df_tags["id"].unique()

array([10, 23, 24, 25, 22, 26,  1, 28, 20, 17, 15, 19,  2, 27, 43, 30],
      dtype=int64)

In [137]:
import numpy as np
df_tags[['id','tags']].describe(include = np.object).transpose()

      count unique     top  freq
tags  40807  20123  [none]  2379

In [138]:
df_1 = df_tags.groupby('id')

df_1.head()

In [139]:
df_1.head()

       id           title_y                                               tags
0      10             Music  Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...
1      10             Music  edsheeran|"ed sheeran"|"acoustic"|"live"|"cove...
2      10             Music  21 savage|"bank account"|"21 savage bank accou...
3      10             Music  punjabi songs|"punjabi bhangra"|"punjabi music...
4      10             Music  Telefoon|"Babbu Maan"|"Mehfil Mitran Di"|"new ...
3731   23            Comedy  plush|"bad unboxing"|"unboxing"|"fan mail"|"id...
3732   23            Comedy  racist superman|"rudy"|"mancuso"|"king"|"bach"...
3733   23            Comedy  Funny Moments|"Montage video games"|"gaming"|"...
3734   23            Comedy      prank|"pranks"|"nelk"|"nelkfilmz"|"nelkfilms"
3735   23            Comedy  danny duncan|"danny duncan 69"|"kevin"|"danny ...
7504   24     Entertainment  ryan|"higa"|"higatv"|"nigahiga"|"i dare you"|"...
7505   24     Entertainment  logan paul vlog|"logan paul"|"logan"|"paul"|"o...
7506   24     Entertainment  twitter|"top 10"|"Taylor Swift"|"YOUTUBERS REA...
7507   24     Entertainment  Graham Norton|"Graham Norton Show Official"|"E...
7508   24     Entertainment  rhett and link|"gmm"|"good mythical morning"|"...
20955  25   News & Politics  #DramaAlert|"Drama"|"Alert"|"DramaAlert"|"keem...
20956  25   News & Politics  Morning Joe|"Joe Scarborough"|"Mika Brzezinski...
20957  25   News & Politics  Duterte News Report|"Philippines News Cast"|"T...
20958  25   News & Politics  news|"Rebel Media"|"RebelMedia"|"UN"|"Climate ...
20959  25   News & Politics  Canada|"CBC"|"CBC News"|"National"|"News"|"The...
25114  22    People & Blogs                                    SHANtell martin
25115  22    People & Blogs               God|"Sheldon Cooper"|"Young Sheldon"
25116  22    People & Blogs  buzzfeed|"buzzfeedblue"|"outsmarted"|"outsmart...
25117  22    People & Blogs  smart girl|"girl"|"how to"|"smart girl shows"|...
25118  22    People & Blogs  Jake|"Paul"|"logan"|"paul"|"its"|"every"|"day"...
29219  26     Howto & Style  sneak food|"how to sneak food into class"|"cla...
29220  26     Howto & Style  jeffree star|"jeffree star cosmetics"|"jeffree...
29221  26     Howto & Style  how to easily make money online|"easily make m...
29222  26     Howto & Style  kitchen gadgets|"best kitchen gadgets"|"gadget...
29223  26     Howto & Style  phone scammer|"phone scams"|"phone scammer pra...
...    ..               ...                                                ...
38572  15    Pets & Animals  shopping for new fish|"new fish"|"aquarium fis...
38573  15    Pets & Animals  ants|"antscanada"|"mikey bustos"|"myrmecology"...
38574  15    Pets & Animals  Aquarium|"aquarium fish"|"uarujoey"|"aquarium ...
38575  15    Pets & Animals  Aquarium|"aquarium fish"|"uarujoey"|"aquarium ...
38576  15    Pets & Animals  aquarium|"frank the flowerhorn"|"flowerhorn"|"...
38941  19   Travel & Events  the food ranger|"trevor james"|"food ranger"|"...
38942  19   Travel & Events                             Emirates|"First Class"
38943  19   Travel & Events  Balinese food|"Bali"|"Indonesia"|"Indonesian f...
38944  19   Travel & Events  Ramen|"Japanese Ramen"|"Chukasoba"|"Chuka-soba...
38945  19   Travel & Events  taiwan street food|"taiwan food"|"best taiwan ...
39333   2  Autos & Vehicles                                             [none]
39334   2  Autos & Vehicles  chevy corvette zr1|"corvette zr1"|"zr1"|"chevy...
39335   2  Autos & Vehicles  Hyundai|"Accent"|"Sedán"|"Comparativa"|"Reseña...
39336   2  Autos & Vehicles  mighty|"car"|"mods"|"moog"|"marty"|"turbo"|"jd...
39337   2  Autos & Vehicles  Hyundai|"Accent"|"Sedán"|"Comparativa"|"Reseña...
39686  27         Education  SciShow|"science"|"Hank"|"Green"|"education"|"...
39687  27         Education  emoji|"emoji movie"|"the emoji movie"|"the emo...
39688  27         Education  dr bot|"docteur bot"|"top 10"|"bete"|"animal"|...
39689  27         Education  American Things Europeans Find Weird|"american...
39690  27         Education  cocoa|"cacao"|"chocolate"|"pod"|"cacao pod"|"b...
40677  43             Shows  deivamagal|"deiva magal"|"deiva magal serial"|...
40678  43             Shows  сериал|"сериал 2017"|"сериал 4к"|"сериал слуга...
40679  43             Shows  сериал|"сериал 2017"|"сериал 4к"|"сериал слуга...
40680  43             Shows  Priyamanaval 16.11.2017|"priyamanaval 866"|"Pr...
40681  43             Shows  сериал|"сериал 2017"|"сериал 4к"|"сериал слуга...
40801  30            Movies  full movie|"full punjabi movie"|"golak"|"bugni...
40802  30            Movies  full movie|"full punjabi movie"|"golak"|"bugni...
40803  30            Movies  full movie|"full punjabi movie"|"golak"|"bugni...
40804  30            Movies  full movie|"full punjabi movie"|"golak"|"bugni...
40805  30            Movies  full movie|"full punjabi movie"|"golak"|"bugni...

[80 rows x 3 columns]

In [232]:
type(df_1)

pandas.core.groupby.generic.DataFrameGroupBy

In [235]:
df_1 = df_1.apply(lambda x : x)

In [236]:
df_1.head()

   id title_y           tags
0  10   Music         Eminem
1  10   Music      edsheeran
2  10   Music      21 savage
3  10   Music  punjabi songs
4  10   Music       Telefoon

In [237]:
type(df_1)
#df_1.apply(lambda x : x)
newdf = pd.DataFrame(df_1.tags.str.split('|').tolist(), index = df_1.id).stack()

In [238]:
newdf.head()

id
10  0           Eminem
    0        edsheeran
    0        21 savage
    0    punjabi songs
    0         Telefoon
dtype: object

In [240]:
newdf = newdf.reset_index([0,"id"])

In [241]:
newdf.head()

   id              0
0  10         Eminem
1  10      edsheeran
2  10      21 savage
3  10  punjabi songs
4  10       Telefoon

In [264]:
newdf.dropna()

       id                                                  0
0      10                                             Eminem
1      10                                          edsheeran
2      10                                          21 savage
3      10                                      punjabi songs
4      10                                           Telefoon
5      10                          Ek Dil Ek Jaan Video Song
6      10                                               Koke
7      10                           Jennifer Lopez ft. Wisin
8      10                                                nav
9      10                                        MEET HUNDAL
10     10                                              Drako
11     10                                             donnie
12     10                                             Davido
13     10                                BPG/RVG/RCA Records
14     10                                             [none]
15     10                                         Gucci Mane
16     10                                      taylor phelan
17     10  New Danchall music world reggae traditional so...
18     10                               post malone rockstar
19     10                                             Eminem
20     10                                                fly
21     10                                               Koke
22     10                                      punjabi songs
23     10                                          21 savage
24     10                                             [none]
25     10                                          edsheeran
26     10                             New punjabi songs 2017
27     10                                           Telefoon
28     10                                        MEET HUNDAL
29     10                                                nav
...    ..                                                ...
40777  43                                    bleacher report
40778  43                            Priyamanaval 18.05.2018
40779  43                                    bleacher report
40780  43                            Priyamanaval 21.05.2018
40781  43                            Priyamanaval 22.05.2018
40782  43                            Priyamanaval 23.05.2018
40783  43                            Priyamanaval 24.05.2018
40784  43                            Priyamanaval 25.05.2018
40785  43                            Priyamanaval 26.05.2018
40786  43                            Priyamanaval 28.05.2018
40787  43                            Priyamanaval 29.05.2018
40788  43                            Priyamanaval 31.05.2018
40789  43                                             Azhagu
40790  43                            Priyamanaval 31.05.2018
40791  43                            Priyamanaval 01.06.2018
40792  43                            Priyamanaval 02.06.2018
40793  43                            Priyamanaval 04.06.2018
40794  43                            Priyamanaval 05.06.2018
40795  43                            Priyamanaval 06.06.2018
40796  43                         Priyamanaval today Episode
40797  43                            Priyamanaval 08.06.2018
40798  43                            Priyamanaval 11.06.2018
40799  43                          priyamanaval episode 1039
40800  43                          priyamanaval episode 1040
40801  30                                         full movie
40802  30                                         full movie
40803  30                                         full movie
40804  30                                         full movie
40805  30                                         full movie
40806  30                                         full movie

[40807 rows x 2 columns]

In [265]:
newdf1 = newdf.groupby("id")

newdf1.head()

In [266]:
newdf1.head(45)

       id                                                  0
0      10                                             Eminem
1      10                                          edsheeran
2      10                                          21 savage
3      10                                      punjabi songs
4      10                                           Telefoon
5      10                          Ek Dil Ek Jaan Video Song
6      10                                               Koke
7      10                           Jennifer Lopez ft. Wisin
8      10                                                nav
9      10                                        MEET HUNDAL
10     10                                              Drako
11     10                                             donnie
12     10                                             Davido
13     10                                BPG/RVG/RCA Records
14     10                                             [none]
15     10                                         Gucci Mane
16     10                                      taylor phelan
17     10  New Danchall music world reggae traditional so...
18     10                               post malone rockstar
19     10                                             Eminem
20     10                                                fly
21     10                                               Koke
22     10                                      punjabi songs
23     10                                          21 savage
24     10                                             [none]
25     10                                          edsheeran
26     10                             New punjabi songs 2017
27     10                                           Telefoon
28     10                                        MEET HUNDAL
29     10                                                nav
...    ..                                                ...
40698  43                                              ON TV
40699  43                     Priyamanaval Episode yesterday
40700  43                                              ON TV
40701  43                            Priyamanaval 07.12.2017
40702  43                            Priyamanaval 08.12.2017
40703  43                            Priyamanaval 09.12.2017
40704  43                                         deivamagal
40705  43                            Priyamanaval 12.12.2017
40706  43                                         deivamagal
40707  43                                         deivamagal
40708  43                                         deivamagal
40709  43                                     sab tv channel
40710  43                            Priyamanaval 18.12.2017
40711  43                            Priyamanaval 21.12.2017
40712  43                                         deivamagal
40713  43                                         deivamagal
40714  43                                         deivamagal
40715  43                                         deivamagal
40716  43                                         deivamagal
40717  43                                         deivamagal
40718  43                                             [none]
40719  43                                         deivamagal
40720  43                                         deivamagal
40721  43                            Priyamanaval 04.01.2018
40801  30                                         full movie
40802  30                                         full movie
40803  30                                         full movie
40804  30                                         full movie
40805  30                                         full movie
40806  30                                         full movie

[681 rows x 2 columns]

In [267]:
newdf2 = newdf1[0].value_counts()

In [277]:
print(newdf2)
newdf2.columns

                                     0
id 0
1  [none]                          117
   電視劇                             116
   Rooster Teeth                   101
   screenjunkies                    56
   Trailer                          49
   Cinema                           37
   琅琊榜之风起长林                         32
   jaiden                           27
   its alex clark                   24
   horror                           23
   Pixar                            22
   leroy                            22
   Lucas the Spider                 20
   Disney                           16
   Senselet                         15
   结爱·千岁大人的初恋                       15
   Anime Zone                       14
   Goldmines Movies                 14
   LucastheSpider                   14
   Yasmine Amari                    14
   南方有乔木                            14
   HBO                              13
   Movie Review                     13
   star wars                        13
   a24                              12
   bạn muốn hẹn hò                  12
   A Boogie                         11
   anime                            11
   tanner fox                       11
   Official Trailer                 10
...                                ...
43 Priyamanaval 12.02.2018           1
   Priyamanaval 12.05.2018           1
   Priyamanaval 12.12.2017           1
   Priyamanaval 14.05.2018           1
   Priyamanaval 15.05.2018           1
   Priyamanaval 16.05.2018           1
   Priyamanaval 16.11.2017           1
   Priyamanaval 17.11.2017           1
   Priyamanaval 18.05.2018           1
   Priyamanaval 18.11.2017           1
   Priyamanaval 18.12.2017           1
   Priyamanaval 20.04.2018           1
   Priyamanaval 21.05.2018           1
   Priyamanaval 21.12.2017           1
   Priyamanaval 22.05.2018           1
   Priyamanaval 23.05.2018           1
   Priyamanaval 24.05.2018           1
   Priyamanaval 25.05.2018           1
   Priyamanaval 26.05.2018           1
   Priyamanaval 28.05.2018           1
   Priyamanaval 29.05.2018           1
   Priyamanaval Episode yesterday    1
   Priyamanaval today Episode        1
   [none]                            1
   priyamanaval 963                  1
   priyamanaval 981                  1
   priyamanaval episode 1039         1
   priyamanaval episode 1040         1
   priyamanaval episode 948          1
   priyamanaval episode 952          1

[9595 rows x 1 columns]

Int64Index([0], dtype='int64')

In [276]:
export_csv1 = newdf2.to_csv (r'youtubeNew1.csv', index = None, header=True)

In [270]:
type(newdf2)

pandas.core.series.Series

In [271]:
newdf2 = pd.DataFrame(newdf2)

In [273]:
type(newdf2)

pandas.core.frame.DataFrame

In [156]:
tags_count = df_tags.groupby('title_y').agg({'tags' : pd.Series.count}).rename(columns = {'title_y' : 'category','tags' : 'count_tags'})

In [157]:
tags_count.head()

                  count_tags
title_y
Autos & Vehicles         353
Comedy                  3773
Education                991
Entertainment          13451
Film & Animation        2060

In [159]:
tags_count.sort_values('count_tags', ascending = False)

                      count_tags
title_y
Entertainment              13451
News & Politics             4159
People & Blogs              4105
Comedy                      3773
Music                       3731
Sports                      2787
Film & Animation            2060
Howto & Style               2007
Gaming                      1344
Science & Technology        1155
Education                    991
Travel & Events              392
Pets & Animals               369
Autos & Vehicles             353
Shows                        124
Movies                         6

In [226]:
from nltk.tokenize import word_tokenize
df1 = df_tags[["tags"]]
df1.head()
df2 = df_tags.tags.str.split("|").str[0]
#tokenized_text = word__tokenize(df_tags[["tags"]])

In [227]:
print(df2)

0                                                   Eminem
1                                                edsheeran
2                                                21 savage
3                                            punjabi songs
4                                                 Telefoon
5                                Ek Dil Ek Jaan Video Song
6                                                     Koke
7                                 Jennifer Lopez ft. Wisin
8                                                      nav
9                                              MEET HUNDAL
10                                                   Drako
11                                                  donnie
12                                                  Davido
13                                     BPG/RVG/RCA Records
14                                                  [none]
15                                              Gucci Mane
16                                           taylor phelan
17       New Danchall music world reggae traditional so...
18                                    post malone rockstar
19                                                  Eminem
20                                                     fly
21                                                    Koke
22                                           punjabi songs
23                                               21 savage
24                                                  [none]
25                                               edsheeran
26                                  New punjabi songs 2017
27                                                Telefoon
28                                             MEET HUNDAL
29                                                     nav
                               ...
40777                                      bleacher report
40778                              Priyamanaval 18.05.2018
40779                                      bleacher report
40780                              Priyamanaval 21.05.2018
40781                              Priyamanaval 22.05.2018
40782                              Priyamanaval 23.05.2018
40783                              Priyamanaval 24.05.2018
40784                              Priyamanaval 25.05.2018
40785                              Priyamanaval 26.05.2018
40786                              Priyamanaval 28.05.2018
40787                              Priyamanaval 29.05.2018
40788                              Priyamanaval 31.05.2018
40789                                               Azhagu
40790                              Priyamanaval 31.05.2018
40791                              Priyamanaval 01.06.2018
40792                              Priyamanaval 02.06.2018
40793                              Priyamanaval 04.06.2018
40794                              Priyamanaval 05.06.2018
40795                              Priyamanaval 06.06.2018
40796                           Priyamanaval today Episode
40797                              Priyamanaval 08.06.2018
40798                              Priyamanaval 11.06.2018
40799                            priyamanaval episode 1039
40800                            priyamanaval episode 1040
40801                                           full movie
40802                                           full movie
40803                                           full movie
40804                                           full movie
40805                                           full movie
40806                                           full movie
Name: tags, Length: 40807, dtype: object

In [202]:
df2_token.head()

0            [Eminem]
1         [edsheeran]
2        [21, savage]
3    [punjabi, songs]
4          [Telefoon]
Name: 0, dtype: object

In [203]:
df2_token = pd.DataFrame(df2_token)

In [204]:
type(df2_token)

pandas.core.frame.DataFrame

In [205]:
list(df2_token.columns.values)

[0]